#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct. 
# docker build --build-arg VCS_REF=`git rev-parse — short HEAD` \
#   --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
#   -t $IMAGE_NAME \
#   -t $DOCKER_REPO/$npm_package_name:$npm_package_version \
#   -t $DOCKER_REPO/$npm_package_name:$npm_package_version-$(date -u '+%Y%m%d-%H%M%S') .
yarn build --build-arg VCS_REF=`git rev-parse — short HEAD` --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”`