#!/bin/bash
export NPM_PACKAGE_NAME=`cat package.json | grep "\"name\"" | cut -d':' -f2 | sed 's/[,|"| ]//g'`
export NPM_PACKAGE_VERSION=`cat package.json | grep "\"version\"" | cut -d':' -f2 | sed 's/[,|"| ]//g'`
#export GIT_SHORT_HASH=`git rev-parse — short HEAD`
export BUILD_DATE=`date -u '+%Y%m%d-%H%M'`
printenv

#docker tag $IMAGE_NAME $DOCKER_REPO:$GIT_SHORT_HASH
#docker push $DOCKER_REPO:$GIT_SHORT_HASH

docker tag $IMAGE_NAME $DOCKER_REPO:$NPM_PACKAGE_VERSION
docker push $DOCKER_REPO:$NPM_PACKAGE_VERSION

docker tag $IMAGE_NAME $DOCKER_REPO:$NPM_PACKAGE_VERSION-$BUILD_DATE
docker push $DOCKER_REPO:$NPM_PACKAGE_VERSION-$BUILD_DATE
